version: "3"
services:
  db:
    image: postgres:latest
    user: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=medigo
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "medigo", "-U", "admin" ]
      interval: 5s
      timeout: 5s
  backend:
    image: "medigo/backend"
    build:
      context: .
      dockerfile: dockerfile.backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - SERVER_PORT=3000
      - DATABASE=medigo
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - DB_HOST=db
      - JWT_SECRET=dsfjirjksdbfk348426378fshkjfsd76328253erew54
    networks:
      - internal  
networks:
  internal:
    name: internal